workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
   
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Flutter analyze
        script: | 
          flutter analyze
      - name: Flutter unit tests
        script: | 
          flutter test
        ignore_failure: true
      - name: yedzav flutter run
        script : |
        flutter build lib/main.dart 
   
    publishing:
      email:
        recipients:
          - jadhavsahil1304@gmail.com
        
        notify:
          success: true
          failure: false
     