workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120

    environment:
      android_signing:
        - keystore_reference
      groups:
        - test

    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: yedzav flutter run
        script: |
          # flutter build apk
          flutter build appbundle --release

      - name: Build universal apk
        script: |
          android-app-bundle build-universal-apk \
          --bundle 'project_directory/build/**/outputs/**/*.aab' \
          --ks /tmp/keystore.keystore \
          --ks-pass $CM_KEYSTORE_PASSWORD \
          --ks-key-alias "sahil" \
          --key-pass $CM_KEY_PASSWORD

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - sangrampaste8897@gmail.com
          - jadhavsahil1304@gmail.com
          - virajkadam007.vk@gmail.com

        notify:
          success: true
          failure: true
