on:
  push:
    branches:
      - main

name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'
          
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: 'true'
      - run: flutter clean    
      - run: flutter upgrade --force
      - run: flutter pub get
      - run: flutter pub upgrade
      - run: flutter build appbundle

      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{secrets.GCP_API_KEY}}
          packageName: com.infimatrix.tradeganit
          releaseFiles: ./build/app/outputs/bundle/release/*.aab
          track: internal
          status: draft
